// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZs1w9K9cVi6WUGPUihLN2C-dsJd40ojI',
    appId: '1:395705090497:android:93a53983bfea7c4e65ef40',
    messagingSenderId: '395705090497',
    projectId: 'poolandchillapp',
    storageBucket: 'poolandchillapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEiuVzr4kQcju-LB2TpGBUCZoY__HG09A',
    appId: '1:395705090497:ios:cfb86d786b2585dd65ef40',
    messagingSenderId: '395705090497',
    projectId: 'poolandchillapp',
    storageBucket: 'poolandchillapp.firebasestorage.app',
    androidClientId: '395705090497-be0gg5jibi9gisjkmtdtep0o7qtrfcnt.apps.googleusercontent.com',
    iosClientId: '395705090497-3rlqeqvuoc2oattpvuv10b5rqde9m1jp.apps.googleusercontent.com',
    iosBundleId: 'com.nextdevcode.poolandchill',
  );
}
